# Generated by Django 2.1.15 on 2020-06-03 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idcops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdu',
            name='rack',
            field=models.ForeignKey(blank=True, help_text='该资源所属的机柜信息', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idcops_pdu_rack', to='idcops.Rack', verbose_name='所属机柜'),
        ),
        migrations.AlterField(
            model_name='rextend',
            name='rack',
            field=models.ForeignKey(blank=True, help_text='该资源所属的机柜信息', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idcops_rextend_rack', to='idcops.Rack', verbose_name='所属机柜'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='rack',
            field=models.ForeignKey(blank=True, help_text='该资源所属的机柜信息', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idcops_unit_rack', to='idcops.Rack', verbose_name='所属机柜'),
        ),
    ]
