# Generated by Django 2.1.15 on 2021-09-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='过保日期'),
        ),
    ]
