# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-30 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idc',
            name='codename',
            field=models.SlugField(default=0, help_text='data center code name for number prefix', verbose_name='code name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idc',
            name='settings',
            field=models.TextField(blank=True, help_text='data center extended settings use json format', verbose_name='settings'),
        ),
        migrations.AddField(
            model_name='user',
            name='settings',
            field=models.TextField(blank=True, help_text='user settings use json format', verbose_name='settings'),
        ),
    ]
