# Generated by Django 2.1.15 on 2021-10-14 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idcops', '0002_device_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='onidc',
            field=models.ForeignKey(blank=True, help_text='该资源所属的机房', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_attachment_onidc', to='idcops.Idc', verbose_name='所属机房'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='该对象的修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_attachment_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='client',
            name='kf',
            field=models.ForeignKey(blank=True, help_text='从机房选项中选取', limit_choices_to={'flag': 'Client-Kf'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_client_kf', to='idcops.Option', verbose_name='客户客服'),
        ),
        migrations.AlterField(
            model_name='client',
            name='onidc',
            field=models.ForeignKey(blank=True, help_text='该资源所属的机房', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_client_onidc', to='idcops.Idc', verbose_name='所属机房'),
        ),
        migrations.AlterField(
            model_name='client',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='该对象的修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_client_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sales',
            field=models.ForeignKey(blank=True, help_text='从机房选项中选取', limit_choices_to={'flag': 'Client-Sales'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_client_sales', to='idcops.Option', verbose_name='客户销售'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='onidc',
            field=models.ForeignKey(blank=True, help_text='该资源所属的机房', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_comment_onidc', to='idcops.Idc', verbose_name='所属机房'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='该对象的修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_comment_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='configure',
            name='onidc',
            field=models.ForeignKey(blank=True, help_text='该资源所属的机房', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_configure_onidc', to='idcops.Idc', verbose_name='所属机房'),
        ),
        migrations.AlterField(
            model_name='configure',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='该对象的修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_configure_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='device',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='设备保修到期日期', null=True, verbose_name='过保日期'),
        ),
        migrations.AlterField(
            model_name='device',
            name='onidc',
            field=models.ForeignKey(blank=True, help_text='该资源所属的机房', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_device_onidc', to='idcops.Idc', verbose_name='所属机房'),
        ),
        migrations.AlterField(
            model_name='device',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='该对象的修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_device_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, help_text='分类, 从机房选项中选取', limit_choices_to={'flag': 'Document-Category'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_document_category', to='idcops.Option', verbose_name='文档分类'),
        ),
        migrations.AlterField(
            model_name='document',
            name='onidc',
            field=models.ForeignKey(blank=True, help_text='该资源所属的机房', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_document_onidc', to='idcops.Idc', verbose_name='所属机房'),
        ),
        migrations.AlterField(
            model_name='document',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='该对象的修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_document_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.ForeignKey(blank=True, help_text='从机房选项中选取', limit_choices_to={'flag': 'Document-Status'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_document_status', to='idcops.Option', verbose_name='文档状态'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='来自机房选项, 标记类型为: 物品分类-生产厂商', limit_choices_to={'flag': 'Goods-Brand'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_goods_brand', to='idcops.Option', verbose_name='生产厂商'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='onidc',
            field=models.ForeignKey(blank=True, help_text='该资源所属的机房', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_goods_onidc', to='idcops.Idc', verbose_name='所属机房'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='该对象的修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_goods_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='该对象的修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_idc_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='client',
            field=models.ForeignKey(blank=True, help_text='该资源所属的客户信息', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_inventory_client', to='idcops.Client', verbose_name='所属客户'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='onidc',
            field=models.ForeignKey(blank=True, help_text='该资源所属的机房', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_inventory_onidc', to='idcops.Idc', verbose_name='所属机房'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='该对象的修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_inventory_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='client',
            field=models.ForeignKey(blank=True, help_text='该资源所属的客户信息', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_ipaddress_client', to='idcops.Client', verbose_name='所属客户'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='onidc',
            field=models.ForeignKey(blank=True, help_text='该资源所属的机房', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_ipaddress_onidc', to='idcops.Idc', verbose_name='所属机房'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='该对象的修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_ipaddress_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='jumpline',
            name='netprod',
            field=models.ForeignKey(blank=True, help_text='电信单线/动态BGP, 字段数据来自机房选项', limit_choices_to={'flag': 'Jumpline-Netprod'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_jumpline_netprod', to='idcops.Option', verbose_name='网络产品'),
        ),
        migrations.AlterField(
            model_name='jumpline',
            name='onidc',
            field=models.ForeignKey(blank=True, help_text='该资源所属的机房', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_jumpline_onidc', to='idcops.Idc', verbose_name='所属机房'),
        ),
        migrations.AlterField(
            model_name='jumpline',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='该对象的修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_jumpline_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='network',
            name='client',
            field=models.ForeignKey(blank=True, help_text='该资源所属的客户信息', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_network_client', to='idcops.Client', verbose_name='所属客户'),
        ),
        migrations.AlterField(
            model_name='network',
            name='onidc',
            field=models.ForeignKey(blank=True, help_text='该资源所属的机房', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_network_onidc', to='idcops.Idc', verbose_name='所属机房'),
        ),
        migrations.AlterField(
            model_name='network',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='该对象的修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_network_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='option',
            name='onidc',
            field=models.ForeignKey(blank=True, help_text='该资源所属的机房', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_option_onidc', to='idcops.Idc', verbose_name='所属机房'),
        ),
        migrations.AlterField(
            model_name='option',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='该对象的修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_option_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='pdu',
            name='client',
            field=models.ForeignKey(blank=True, help_text='该资源所属的客户信息', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_pdu_client', to='idcops.Client', verbose_name='所属客户'),
        ),
        migrations.AlterField(
            model_name='pdu',
            name='onidc',
            field=models.ForeignKey(blank=True, help_text='该资源所属的机房', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_pdu_onidc', to='idcops.Idc', verbose_name='所属机房'),
        ),
        migrations.AlterField(
            model_name='pdu',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='该对象的修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_pdu_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='client',
            field=models.ForeignKey(blank=True, help_text='该资源所属的客户信息', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_rack_client', to='idcops.Client', verbose_name='所属客户'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='onidc',
            field=models.ForeignKey(blank=True, help_text='该资源所属的机房', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_rack_onidc', to='idcops.Idc', verbose_name='所属机房'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='该对象的修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_rack_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='status',
            field=models.ForeignKey(blank=True, help_text='从机房选项中选取 机柜状态', limit_choices_to={'flag': 'Rack-Status'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_rack_status', to='idcops.Option', verbose_name='机柜状态'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='style',
            field=models.ForeignKey(blank=True, help_text='从机房选项中选取 机柜类型', limit_choices_to={'flag': 'Rack-Style'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_rack_style', to='idcops.Option', verbose_name='机柜类型'),
        ),
        migrations.AlterField(
            model_name='rextend',
            name='client',
            field=models.ForeignKey(blank=True, help_text='该资源所属的客户信息', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_rextend_client', to='idcops.Client', verbose_name='所属客户'),
        ),
        migrations.AlterField(
            model_name='rextend',
            name='onidc',
            field=models.ForeignKey(blank=True, help_text='该资源所属的机房', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_rextend_onidc', to='idcops.Idc', verbose_name='所属机房'),
        ),
        migrations.AlterField(
            model_name='rextend',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='该对象的修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_rextend_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='syslog',
            name='onidc',
            field=models.ForeignKey(blank=True, help_text='该资源所属的机房', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_syslog_onidc', to='idcops.Idc', verbose_name='所属机房'),
        ),
        migrations.AlterField(
            model_name='syslog',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='该对象的修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_syslog_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='testapply',
            name='onidc',
            field=models.ForeignKey(blank=True, help_text='该资源所属的机房', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_testapply_onidc', to='idcops.Idc', verbose_name='所属机房'),
        ),
        migrations.AlterField(
            model_name='testapply',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='该对象的修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_testapply_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='client',
            field=models.ForeignKey(blank=True, help_text='该资源所属的客户信息', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_unit_client', to='idcops.Client', verbose_name='所属客户'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='onidc',
            field=models.ForeignKey(blank=True, help_text='该资源所属的机房', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_unit_onidc', to='idcops.Idc', verbose_name='所属机房'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='该对象的修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_unit_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='user',
            name='onidc',
            field=models.ForeignKey(blank=True, help_text='该资源所属的机房', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_user_onidc', to='idcops.Idc', verbose_name='所属机房'),
        ),
        migrations.AlterField(
            model_name='zonemap',
            name='onidc',
            field=models.ForeignKey(blank=True, help_text='该资源所属的机房', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_zonemap_onidc', to='idcops.Idc', verbose_name='所属机房'),
        ),
        migrations.AlterField(
            model_name='zonemap',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='该对象的修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_zonemap_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
    ]
