# Generated by Django 2.1.15 on 2020-10-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcops', '0002_auto_20200603_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='urange',
            field=models.CharField(blank=True, help_text='U位起始到结束，比如：05-08', max_length=12, null=True, verbose_name='U位范围'),
        ),
    ]
