# Generated by Django 2.1.15 on 2021-11-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcops', '0004_device_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='机柜合同到期日期', null=True, verbose_name='到期时间'),
        ),
    ]
