# Generated by Django 2.1.15 on 2020-11-20 14:47

from django.db import migrations, models
import django.db.models.deletion
import idcops.lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('idcops', '0004_auto_20201117_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='network',
            options={'default_permissions': ('view', 'add', 'change', 'delete', 'exports'), 'verbose_name': '网络管理', 'verbose_name_plural': '网络管理'},
        ),
        migrations.RemoveField(
            model_name='network',
            name='dhcp_broadcast',
        ),
        migrations.RemoveField(
            model_name='network',
            name='reserved_from_beginning',
        ),
        migrations.RemoveField(
            model_name='network',
            name='reserved_from_end',
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='address',
            field=models.GenericIPAddressField(help_text='例如：172.16.21.1', verbose_name='IP 地址'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='hostname',
            field=idcops.lib.fields.NullableCharField(blank=True, default=None, max_length=255, null=True, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='is_gateway',
            field=models.BooleanField(default=False, verbose_name='网关地址'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='is_management',
            field=models.BooleanField(default=False, verbose_name='管理地址'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='is_public',
            field=models.BooleanField(default=False, editable=False, verbose_name='公有地址'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='network',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_ipaddress_network', to='idcops.Network', verbose_name='所属网域'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='number',
            field=models.DecimalField(decimal_places=0, default=None, editable=False, help_text='IP地址的整数形式', max_digits=39, unique=True, verbose_name='IP号'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='status',
            field=models.NullBooleanField(default=None, help_text='如果IP地址已被使用，则值为True', verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='network',
            name='address',
            field=idcops.lib.fields.IPNetwork(help_text='以字符串形式显示（例如172.16.21.0/24）', max_length=44, unique=True, verbose_name='网络地址'),
        ),
        migrations.AlterField(
            model_name='network',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_network_gateway', to='idcops.IPAddress', verbose_name='网关地址'),
        ),
        migrations.AlterField(
            model_name='network',
            name='is_public',
            field=models.BooleanField(default=None, editable=False, verbose_name='公有地址'),
        ),
        migrations.AlterField(
            model_name='network',
            name='kind',
            field=models.ForeignKey(blank=True, help_text='从机房选项中新建选择', limit_choices_to={'flag__icontains': 'Network-Kind'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcops_network_kind', to='idcops.Option', verbose_name='网络类型'),
        ),
        migrations.AlterField(
            model_name='network',
            name='max_ip',
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=39, verbose_name='最大IP号码'),
        ),
        migrations.AlterField(
            model_name='network',
            name='min_ip',
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=39, verbose_name='最小IP号码'),
        ),
        migrations.AlterField(
            model_name='network',
            name='vlan',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='VLAN ID'),
        ),
    ]
