# Generated by Django 2.1.15 on 2020-11-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcops', '0005_auto_20201120_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='parent',
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='number',
            field=models.DecimalField(decimal_places=0, default=None, editable=False, help_text='IP地址的整数形式', max_digits=39, verbose_name='IP号'),
        ),
    ]
