# Generated by Django 2.1.15 on 2020-11-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcops', '0006_auto_20201120_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='check_hosts',
            field=models.BooleanField(default=True, help_text='ping 子网内的主机以检查可用性', verbose_name='检查主机'),
        ),
        migrations.AddField(
            model_name='network',
            name='discovery_hosts',
            field=models.BooleanField(default=True, help_text='通过ICMP协议发现子网中新主机', verbose_name='自动发现'),
        ),
        migrations.AddField(
            model_name='network',
            name='vrf',
            field=models.CharField(blank=True, help_text='Virtual Routing and Forwarding，虚拟路由转发', max_length=32, null=True, verbose_name='VRF'),
        ),
        migrations.AlterField(
            model_name='network',
            name='max_ip',
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=39, verbose_name='最大IP号'),
        ),
        migrations.AlterField(
            model_name='network',
            name='min_ip',
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=39, verbose_name='最小IP号'),
        ),
    ]
